In [12]:
import pandas as pd

In [13]:
sa = pd.read_csv('../data/attacks.csv', encoding='latin1')

In [14]:
sa.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25614 entries, 0 to 25613
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Case Number             6095 non-null   object
 1   Date                    6094 non-null   object
 2   Year                    6092 non-null   float64
 3   Type                    6090 non-null   object
 4   Country                 6048 non-null   object
 5   Area                    5682 non-null   object
 6   Location                5583 non-null   object
 7   Activity                5559 non-null   object
 8   Name                    5888 non-null   object
 9   Sex                     5517 non-null   object
 10  Age                     3374 non-null   object
 11  Injury                  6066 non-null   object
 12  Fatal (Y/N)             6064 non-null   object
 13  Time                    2848 non-null   object
 14  Species                 3100 non-null   object
 15  Investigator or Source  6077 non-null   object
 16  pdf                     6094 non-null   object
 17  href formula            6093 non-null   object
 18  href                    6093 non-null   object
 19  Case Number.1           6094 non-null   object
 20  Case Number.2           6094 non-null   object
 21  original order          6094 non-null   float64
dtypes: float64(2), object(20)
memory usage: 4.3+ MB

In [15]:
sa.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order'],
      dtype='object')

In [16]:
sa = sa.rename(columns={'Case Number': 'Números de Caso', 
                        'Date':'Data',
                        'Year':'Ano',
                        'Type': 'Tipo de Ataque',
                        'Country':'País',
                        'Area' : 'Área',
                        'Location':'Localização',
                        'Activity':'Atividade',
                        'Name':'Nome da Vítima',
                        'Sex ' :'Sexo',
                        'Age':'Idade',
                        'Injury':'Injúria',
                        'Fatal (Y/N)':'Fatal (S/N)',
                        'Time':'Hora',
                        'Species ':'Espécies',
                        'Investigator or Source':'Investigador ou Fonte',
                        'pdf':'pdf',
                        'href formula':'fórmula href',
                        'href':'href',
                        'Case Number.1':'Número do Caso.1',
                        'Case Number.2':'Número do Caso.2',
                        'original order':'ordem original'


                        })

In [17]:
sa.columns

Index(['Números de Caso', 'Data', 'Ano', 'Tipo de Ataque', 'País', 'Área',
       'Localização', 'Atividade', 'Nome da Vítima', 'Sexo', 'Idade',
       'Injúria', 'Fatal (S/N)', 'Hora', 'Espécies', 'Investigador ou Fonte',
       'pdf', 'fórmula href', 'href', 'Número do Caso.1', 'Número do Caso.2',
       'ordem original'],
      dtype='object')

In [18]:
sa.head()

,Números de Caso,Data,Ano,Tipo de Ataque,País,Área,Localização,Atividade,Nome da Vítima,Sexo,...,Fatal (S/N),Hora,Espécies,Investigador ou Fonte,pdf,fórmula href,href,Número do Caso.1,Número do Caso.2,ordem original
0,2017.06.11,2017-06-11,2017.0,Unprovoked,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,...,N,08h30,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.11,2017.06.11,6095.0
1,2017.06.10.b,2017-06-10,2017.0,Unprovoked,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,...,N,15h45,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.10.b,2017.06.10.b,6094.0
2,2017.06.10.a,2017-06-10,2017.0,Unprovoked,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,...,N,10h00,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.10.a,2017.06.10.a,6093.0
3,2017.06.07.R,Reported 07-Jun-2017,2017.0,Unprovoked,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,...,N,NaN,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.07.R,2017.06.07.R,6092.0
4,2017.06.04,2017-06-04,2017.0,Unprovoked,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,...,N,NaN,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.04,2017.06.04,6091.0

In [19]:
sa['Fatal (S/N)'] = sa['Fatal (S/N)'].astype("string").str.strip().str.upper()


sa['Fatal (S/N)'] = sa['Fatal (S/N)'].replace({
    "Y": "Sim",
    "N": "Não",
    "SIM": "Sim",
    "NÃO": "Não",
    "NAO": "Não",
    "UNKNOWN": pd.NA,
    "F": pd.NA,
    "#VALUE!": pd.NA,
    "2017": pd.NA,
    "<NA>": pd.NA
})

In [20]:
sa["Fatal (S/N)"].value_counts(dropna=False)

Fatal (S/N)
<NA>    19647
Não      4401
Sim      1566
Name: count, dtype: Int64

In [21]:
sa['Ano'].value_counts(dropna=False)

Ano
NaN       19522
2015.0      141
2016.0      128
2011.0      128
2014.0      126
          ...
1787.0        1
1786.0        1
1785.0        1
1774.0        1
1807.0        1
Name: count, Length: 241, dtype: int64

In [22]:
sa['Ano'] = pd.to_numeric(sa['Ano'], errors='coerce').astype('Int64')
sa.loc[(sa['Ano'] < 1500) | (sa['Ano'] > 2026), 'Ano'] = pd.NA

sa['Ano'].value_counts(dropna=False).sort_index()

Ano
1543        1
1554        1
1555        1
1580        1
1595        1
        ...
2014      126
2015      141
2016      128
2017       54
<NA>    19649
Name: count, Length: 237, dtype: Int64

In [23]:
sa['Tipo de Ataque'].value_counts(dropna=False)

Tipo de Ataque
NaN             19524
Unprovoked       4466
Provoked          563
Invalid           529
Sea Disaster      220
Boat              202
Boating           110
Name: count, dtype: int64

In [24]:
sa['Tipo de Ataque'] = sa['Tipo de Ataque'].replace({
    'Unprovoked': 'Não provocado',
    'Provoked': 'Provocado',
    'Boat': 'Embarcação',
    'Boating': 'Embarcação',
    'Sea Disaster': 'Desastre marítimo',
    'Invalid': 'Inválido'
})
sa['Tipo de Ataque'].value_counts(dropna=False)

Tipo de Ataque
NaN                  19524
Não provocado         4466
Provocado              563
Inválido               529
Embarcação             312
Desastre marítimo      220
Name: count, dtype: int64

In [25]:
sa.head()

,Números de Caso,Data,Ano,Tipo de Ataque,País,Área,Localização,Atividade,Nome da Vítima,Sexo,...,Fatal (S/N),Hora,Espécies,Investigador ou Fonte,pdf,fórmula href,href,Número do Caso.1,Número do Caso.2,ordem original
0,2017.06.11,2017-06-11,2017,Não provocado,AUSTRALIA,Western Australia,"Point Casuarina, Bunbury",Body boarding,Paul Goff,M,...,Não,08h30,"White shark, 4 m","WA Today, 6/11/2017",2017.06.11-Goff.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.11,2017.06.11,6095.0
1,2017.06.10.b,2017-06-10,2017,Não provocado,AUSTRALIA,Victoria,"Flinders, Mornington Penisula",Surfing,female,F,...,Não,15h45,7 gill shark,NaN,2017.06.10.b-Flinders.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.10.b,2017.06.10.b,6094.0
2,2017.06.10.a,2017-06-10,2017,Não provocado,USA,Florida,"Ponce Inlet, Volusia County",Surfing,Bryan Brock,M,...,Não,10h00,NaN,"Daytona Beach News-Journal, 6/10/2017",2017.06.10.a-Brock.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.10.a,2017.06.10.a,6093.0
3,2017.06.07.R,Reported 07-Jun-2017,2017,Não provocado,UNITED KINGDOM,South Devon,Bantham Beach,Surfing,Rich Thomson,M,...,Não,NaN,"3m shark, probably a smooth hound","C. Moore, GSAF",2017.06.07.R-Thomson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.07.R,2017.06.07.R,6092.0
4,2017.06.04,2017-06-04,2017,Não provocado,USA,Florida,"Middle Sambo Reef off Boca Chica, Monroe County",Spearfishing,Parker Simpson,M,...,Não,NaN,8' shark,"Nine News, 6/7/2017",2017.06.04-Simpson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2017.06.04,2017.06.04,6091.0

In [26]:
sa['Data'] = sa['Data'].astype(str).str.replace('Reported ', '', regex=False)
sa['Data'].value_counts(dropna=False)

Data
nan                                   19520
1905-05-10                               11
1905-04-25                                9
1905-05-09                                8
1905-05-03                                7
                                      ...
1993-12-01                                1
1905-06-16                                1
Last incident of 1994 in Hong Kong        1
1994-01-03                                1
1975-10-04                                1
Name: count, Length: 5193, dtype: int64

In [27]:
sa['Data'] = sa['Data'].astype('string')

sa["Data"] = sa["Data"].str.replace("Reported ", "", regex=False)
sa["Data"] = sa["Data"].str.replace("Last incident of ", "", regex=False)
sa["Data"] = sa["Data"].str.replace("Before ", "", regex=False)
sa["Data"] = sa["Data"].str.replace("Ca. ", "", regex=False)
sa["Data"] = sa["Data"].str.strip()

sa["Data"] = pd.to_datetime(sa["Data"], errors="coerce")

sa["Data"].value_counts(dropna=False)

Data
NaT           20654
1905-05-10       11
1905-04-25        9
1905-05-09        8
1905-05-11        7
              ...
1998-10-10        1
1998-10-04        1
1998-09-27        1
1998-09-22        1
1904-04-03        1
Name: count, Length: 4156, dtype: int64

In [28]:
sa["idade_limpa"] = sa["Idade"].astype(str).str.lower().str.strip()
sa.loc[sa["idade_limpa"].str.contains("month"), "idade_limpa"] = (
    sa["idade_limpa"].str.extract(r"(\d+)").astype(float) / 12
)
sa["idade_limpa"] = sa["idade_limpa"].str.extract(r"(\d+\.?\d*)", expand=False)
sa["Idade"] = pd.to_numeric(sa["idade_limpa"], errors="coerce")
sa.loc[(sa["Idade"] < 0) | (sa["Idade"] > 100), "Idade"] = pd.NA
sa["Idade"].value_counts(dropna=False).sort_index()

Idade
1.0         2
2.0         1
3.0         4
5.0         7
6.0        15
        ...
81.0        1
84.0        1
86.0        1
87.0        1
NaN     22275
Name: count, Length: 81, dtype: int64

In [29]:
sa['Sexo'].value_counts(dropna=False)

Sexo
NaN    20097
M       4906
F        606
M          2
lli        1
N          1
.          1
Name: count, dtype: int64

In [30]:
sa['Sexo'] = sa['Sexo'].astype(str).str.strip().str.upper()
sa['Sexo'] = sa['Sexo'].replace({
    'M': 'Masculino',
    'F': 'Feminino',
    'N': pd.NA,
    '.': pd.NA,
    'LLI': pd.NA,
    'NAN': pd.NA
})
sa['Sexo'].value_counts(dropna=False)

Sexo
<NA>         20100
Masculino     4908
Feminino       606
Name: count, dtype: int64

In [31]:
sa['Hora'].value_counts(dropna=False)

Hora
NaN                 22766
Afternoon             181
11h00                 126
Morning               112
12h00                 108
                    ...
13h53                   1
13h23                   1
Just after 12h00        1
02h30                   1
19h00-20h00             1
Name: count, Length: 361, dtype: int64

In [32]:
sa['Hora'] = sa['Hora'].astype("string").str.strip().str.lower()
import re

def limpar_hora(valor):
    if pd.isna(valor):
        return pd.NA

    # pega padrão tipo 11h00, 02h30, 19:00
    match = re.search(r'(\d{1,2})[:h](\d{2})', valor)
    if match:
        h = int(match.group(1))
        m = int(match.group(2))
        if 0 <= h <= 23 and 0 <= m <= 59:
            return f"{h:02d}:{m:02d}"

    return pd.NA
sa['Hora_Limpa'] = sa['Hora'].apply(limpar_hora)
sa['Hora_Limpa'].value_counts(dropna=False)

Hora_Limpa
<NA>     23323
11:00      129
12:00      112
15:00      103
16:00       98
         ...
13:42        1
11:11        1
15:53        1
14:21        1
01:50        1
Name: count, Length: 244, dtype: int64

In [33]:
sa['Espécies'].value_counts(dropna=False)

Espécies
NaN                                           22514
White shark                                     164
Shark involvement not confirmed                  81
Tiger shark                                      73
Bull shark                                       53
                                              ...
2.5 m [8.25'] white shark                         1
said to involve an oceanic whitetip shark         1
1.8 m to 2.1 m [6' to 7'] hammerhead shark        1
Tiger shark, 2.4 m [8']                           1
N                                                 1
Name: count, Length: 1556, dtype: int64

In [34]:
sa['Espécies'] = sa['Espécies'].astype("string").str.strip().str.lower()
import re

def limpar_especie(valor):
    if pd.isna(valor):
        return pd.NA

    v = valor.lower()

    if "white shark" in v or "great white" in v:
        return "White Shark"
    if "tiger shark" in v:
        return "Tiger Shark"
    if "bull shark" in v:
        return "Bull Shark"
    if "hammerhead" in v:
        return "Hammerhead Shark"
    if "whitetip" in v:
        return "Oceanic Whitetip Shark"
    if "reef shark" in v:
        return "Reef Shark"
    if "blacktip" in v:
        return "Blacktip Shark"
    if "nurse shark" in v:
        return "Nurse Shark"
    if "blue shark" in v:
        return "Blue Shark"
    if "mako shark" in v:
        return "Mako Shark"
    if "lemon shark" in v:
        return "Lemon Shark"
    if "sand tiger" in v:
        return "Sand Tiger Shark"
    if "galapagos shark" in v:
        return "Galapagos Shark"
    if "silky shark" in v:
        return "Silky Shark"

    if "shark involvement not confirmed" in v:
        return pd.NA

    if v in ["n", ".", "unknown"]:
        return pd.NA

    return "Other Shark"
sa['Especie_Limpa'] = sa['Espécies'].apply(limpar_especie)
sa['Especie_Limpa'].value_counts(dropna=False)

Especie_Limpa
<NA>                      22604
Other Shark                1461
White Shark                 627
Tiger Shark                 291
Bull Shark                  170
Nurse Shark                  94
Blacktip Shark               91
Reef Shark                   63
Mako Shark                   55
Hammerhead Shark             48
Blue Shark                   40
Lemon Shark                  34
Oceanic Whitetip Shark       26
Galapagos Shark               6
Silky Shark                   4
Name: count, dtype: int64

In [35]:
sa['Nome da Vítima'].value_counts(dropna=False)

Nome da Vítima
NaN                19726
male                 506
female                90
boy                   23
boat                  14
                   ...
Megan O'Leary          1
Andy Thompson          1
Healy Lootz            1
Donna Turcotte         1
Jules Patterson        1
Name: count, Length: 5087, dtype: int64

In [36]:
sa['Nome da Vítima'] = sa['Nome da Vítima'].astype("string").str.strip()
import re

def limpar_nome(valor):
    if pd.isna(valor):
        return pd.NA

    v = valor.strip()

    lixo = ['male', 'female', 'boy', 'girl', 'man', 'woman', 'boat', 'unknown'  ]

    if v.lower() in lixo:
        return pd.NA

    if len(v) < 3:
        return pd.NA

    if not re.search(r"[a-zA-Z]", v):
        return pd.NA

    return v.title()
sa['Nome_Limpo'] = sa['Nome da Vítima'].apply(limpar_nome)
sa[['Nome da Vítima','Nome_Limpo']].sample(10)
sa['Nome_Limpo'].value_counts(dropna=False)

Nome_Limpo
<NA>                                20383
2 Males                                16
Anonymous                              12
Sailor                                 11
Child                                  10
                                    ...
Evan Ridge                              1
Rajkumar Mansaram                       1
28' Sport Fishing Boat, Bird Dog        1
Robyne Knutson                          1
Jules Patterson                         1
Name: count, Length: 5063, dtype: int64

In [37]:
sa['País'].value_counts(dropna=False)

País
NaN                       19566
USA                        2160
AUSTRALIA                  1303
SOUTH AFRICA                571
PAPUA NEW GUINEA            133
                          ...
NORTH SEA                     1
RED SEA / INDIAN OCEAN        1
BRITISH WEST INDIES           1
ADMIRALTY ISLANDS             1
CEYLON (SRI LANKA)            1
Name: count, Length: 205, dtype: int64